'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class mxentdbEntities
    Inherits DbContext
    Public Sub New(strConn As String)
        MyBase.New(strConn)
    End Sub

    Public Sub New()
        MyBase.New("name=mxentdbEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property PersEdus() As DbSet(Of PersEdu)
    Public Overridable Property PersFamilies() As DbSet(Of PersFamily)
    Public Overridable Property Persons() As DbSet(Of Person)

End Class
