'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PersEdu
    Public Property PersEduID As Integer
    Public Property PersonID As Nullable(Of Integer)
    Public Property Qualification As String
    Public Property Institution As String
    Public Property YearQual As String
    Public Property Marks As Nullable(Of Decimal)

    Public Overridable Property Person As Person

End Class
