'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PersFamily
    Public Property PersFamilyID As Integer
    Public Property PersonID As Nullable(Of Integer)
    Public Property MemberName As String
    Public Property Relation As String
    Public Property BDate As Nullable(Of Date)
    Public Property Profession As String
    Public Property Other As String

    Public Overridable Property Person As Person

End Class
