'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Person
    Public Property PersonID As Integer
    Public Property Salutation As String
    Public Property FirstName As String
    Public Property MidName As String
    Public Property LastName As String
    Public Property FullName As String
    Public Property NickName As String
    Public Property Sex As String
    Public Property MarStatus As String
    Public Property IsFemale As Nullable(Of Boolean)
    Public Property Email As String
    Public Property CellNum As String
    Public Property Remark As String
    Public Property Education As String
    Public Property Profile As String
    Public Property Birthday As Nullable(Of Date)
    Public Property Anniversary As Nullable(Of Date)
    Public Property PrAddress As String
    Public Property PrCity As String
    Public Property PrState As String
    Public Property PrCountry As String
    Public Property PrPinCode As String
    Public Property OfficeCountry As String
    Public Property OfficeArea As String
    Public Property OfficePhone As String
    Public Property PrPhCountry As String
    Public Property PrPhArea As String
    Public Property PrPhone As String
    Public Property Web As String
    Public Property LastUpdated As Nullable(Of Date)
    Public Property PmAddress As String
    Public Property PmCity As String
    Public Property PmState As String
    Public Property PmCountry As String
    Public Property PmPinCode As String
    Public Property PmPhCountry As String
    Public Property PmPhArea As String
    Public Property PmPhone As String
    Public Property PicPerson As Byte()
    Public Property FingerPrint As Byte()
    Public Property TempEmpID As Nullable(Of Integer)
    Public Property TopQual As String
    Public Property OtherExp As Nullable(Of Decimal)
    Public Property PrStateCode As String
    Public Property PrCountryCode As String
    Public Property PmStateCode As String
    Public Property PmCountryCode As String
    Public Property PrMailingAddress As String
    Public Property PmMailingAddress As String

    Public Overridable Property PersEdus As ICollection(Of PersEdu) = New HashSet(Of PersEdu)
    Public Overridable Property PersFamilies As ICollection(Of PersFamily) = New HashSet(Of PersFamily)

End Class
