//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace risersoft.app.mxform.cog.Models
{
    using risersoft.shared;
    using System;
    using System.Collections.Generic;
    
    public partial class BotGroupOption:BaseType
    {
        public Nullable<System.Guid> BotId { get; set; }
        public string ChannelKey { get; set; }
        public string ConversationId { get; set; }
    }
}
